package constants

const API_GET_GET_LIVE_NODE_URL = "/ns/api/nodes/live"
const BROKER_MSG_SUBSCRIBE = "SUBSCRIBE"
const BROKER_MSG_PUBLISH = "PUBLISH"
const BROKER_MSG_AUTHENTICATE="AUTHENTICATE"

const BROKER_MSG_SUBSCRIBE_PAYLOAD_TOPIC = "topic"
const BROKER_MSG_PUBLISH_PAYLOAD_TOPIC = "topic"
const BROKER_MSG_PUBLISH_PAYLOAD_MSG = "msg"
const BROKER_MSG_PUBLISH_PAYLOAD_MASTERCLID ="master-clid"
const BROKER_MSG_PUBLISH_PAYLOAD_MASTERTOKEN ="master-tkn"
const BROKER_MSG_PUBLISH_PAYLOAD_XTOKEN="X-Token"
const BROKER_MSG_PUBLISH_PAYLOAD_XDEVICEID="X-DeviceID"
const BROKER_MSG_PUBLISH_PAYLOAD_XUID="X-UID"


